baseURL = "https://ldoughty.com/"
enableRobotsTXT = true
languageCode = "en-us"
title = "Lee Doughty"
author = "Lee Doughty"
canonifyurls = true
#paginate = 3
theme = "silhouette-hugo"
uglyurls = false

pygmentsUseClasses=true

#disqusShortname = ""
#googleAnalytics = ""



[Params]
rssFeed = true
author = "Lee Doughty"
introDescription = "I'm Lee Doughty, Senior Cloud Systems Engineer at the Virginia Cyber Range and all-around geek."
copyrightBy = "Lee Doughty"
copyrightLongNotice = "Articles, Text, and Images are Copyright © 2018–2019 by Lee Doughty."

#twitterLink = "https://twitter.com/leemdoughty"
#instagramLink = ""
linkedInLink = "https://www.linkedin.com/in/ldoughty"


[social]
#instagram = ""
linkedin = "ldoughty"
#twitter = "leemdoughty"

[permalinks]
post = "/:year/:month/:title/"
